OPENAI_API = "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"
DALLE_TEXT = "Generate a prompt for dall-e to create a realistic scary traumatising image which shows a deep message. Make sure the prompt is in english language."